# Project Context - Architecture
# Generated by: asimov init --type arch
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: arch
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  lint: "markdownlint-cli2 '**/*.md'"
  fix: "markdownlint-cli2 --fix '**/*.md'"
  diagrams: "Mermaid/PlantUML validation (optional)"

files:
  architecture:
    - "ARCHITECTURE_OVERVIEW.md - System overview"
    - "c4-models/ - C4 architecture diagrams"
    - "diagrams/ - Mermaid/PlantUML diagrams"
  decisions:
    - "decisions/ - Architecture Decision Records"
  docs:
    - "README.md - Project documentation"
    - "GLOSSARY.md - Domain terminology"
  config:
    - ".markdownlint.yaml - Lint configuration"

patterns:
  - "C4 model diagrams (Context, Container, Component, Code)"
  - "ADRs for significant decisions"
  - "Mermaid for text-based diagrams (version controlled)"
  - "One sentence per line (for git diffs)"

c4_structure:
  levels:
    - context: "System context - how system fits in the world"
    - container: "High-level tech choices (apps, DBs, etc.)"
    - component: "Components within each container"
    - code: "Class/module level (if needed)"
  tools:
    - "Structurizr DSL"
    - "Mermaid C4"
    - "PlantUML C4"

# v9.3.0: Coding standards for architecture projects (ADR-041)
coding_standards:
  file_size:
    soft_limit: 500
    note: "lines per markdown file - keep docs focused"
  linting: "markdownlint, yamllint for configs"
  diagrams: "Mermaid preferred (text-based, version controlled)"
  consistency:
    - "Use consistent terminology (see GLOSSARY.md)"
    - "Keep diagrams up to date with code changes"
    - "One ADR per significant decision"

# v8.8.0: Standard deliverables for architecture projects (ADR-034)
deliverables_template:
  - "[ ] Architecture diagrams updated"
  - "[ ] ADR written for significant decisions"
  - "[ ] asimov lint-docs . (passes)"
  - "[ ] Diagrams render correctly"
  - "[ ] Commit and push"
