# Project Context - Flutter / Dart
# Generated by: asimov init --type flutter
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: flutter
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"
  visibility: "PRIVATE - check publish_to in pubspec.yaml"

quality:
  test: "flutter test"
  lint: "dart analyze lib/"
  format: "dart format lib/ test/"
  build_android: "flutter build apk"
  build_ios: "flutter build ios"

files:
  source:
    - "lib/main.dart - App entry point"
    - "lib/src/ - Source code"
    - "lib/widgets/ - Reusable widgets"
    - "lib/screens/ - Screen widgets"
    - "lib/services/ - Business logic"
  config:
    - "pubspec.yaml - Dependencies"
    - "analysis_options.yaml - Lint rules"
  tests:
    - "test/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "60fps minimum - no jank"
  - "Const constructors where possible"
  - "Split large widgets into smaller components"
  - "Use RepaintBoundary for expensive widgets"

platform:
  cupertino_first: "CupertinoPageScaffold, CupertinoNavigationBar, CupertinoButton"
  material_fallback: "Only when Cupertino unavailable"

# v9.3.0: Coding standards for Flutter projects (ADR-041)
coding_standards:
  code:
    file_size:
      soft_limit: 400
      hard_limit: 800
      note: "lines per file - split widgets if exceeding"
    coverage: "80%+"
    linting: "dart analyze, very_good_analysis recommended"
    tests: "widget tests, unit tests, integration tests"
    formatting: "dart format"
    performance: "60fps minimum, const constructors"
  documentation:
    linting: "markdownlint-cli2"
    style:
      - "ATX-style headers (#)"
      - "One sentence per line (for git diffs)"
  architecture:
    decisions: "ADR format in docs/adr/"
    diagrams: "Mermaid preferred (text-based, version controlled)"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass (flutter test)"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] dart analyze lib/ (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
