# Project Context - Go
# Generated by: asimov init --type go
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: go
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "go test ./..."
  lint: "golangci-lint run"
  format: "go fmt ./..."
  vet: "go vet ./..."
  build: "go build -o bin/app"

files:
  source:
    - "main.go - Entry point"
    - "cmd/ - CLI commands"
    - "internal/ - Private packages"
    - "pkg/ - Public packages"
  config:
    - "go.mod - Module definition"
    - "go.sum - Dependency checksums"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Return errors, don't panic"
  - "Accept interfaces, return structs"
  - "Keep packages small and focused"
  - "Use context for cancellation"

release:
  static_binary: "CGO_ENABLED=0 go build"
  compression: "UPX --best --lzma (optional)"

# v9.3.0: Coding standards for Go projects (ADR-041)
coding_standards:
  code:
    file_size:
      soft_limit: 500
      hard_limit: 1000
      note: "lines per file - split if exceeding"
    coverage: "80%+"
    linting: "golangci-lint (golint, errcheck, staticcheck)"
    tests: "table-driven tests, *_test.go files"
    formatting: "gofmt"
  documentation:
    linting: "markdownlint-cli2"
    style:
      - "ATX-style headers (#)"
      - "One sentence per line (for git diffs)"
  architecture:
    decisions: "ADR format in docs/adr/"
    diagrams: "Mermaid preferred (text-based, version controlled)"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass (go test ./...)"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] golangci-lint run (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
