# Project Context - Documentation
# Generated by: asimov init --type docs
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: docs
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  lint: "markdownlint-cli2 '**/*.md'"
  fix: "markdownlint-cli2 --fix '**/*.md'"
  links: "lychee --offline '**/*.md' (optional)"

files:
  docs:
    - "README.md - Main documentation"
    - "docs/ - Additional documentation"
    - "docs/adr/ - Architecture Decision Records"
  config:
    - ".markdownlint.yaml - Lint configuration"
  diagrams:
    - "docs/diagrams/ - Mermaid or PlantUML"

patterns:
  - "Use ATX-style headers (#)"
  - "One sentence per line (for git diffs)"
  - "Use Mermaid for diagrams (text-based)"
  - "Keep documentation concise"

adr_format:
  template: |
    # ADR-NNN: Title

    **Status:** Proposed | Accepted | Deprecated | Superseded
    **Date:** YYYY-MM-DD
    **Deciders:** Names

    ## Context
    ## Decision
    ## Consequences

# v9.3.0: Coding standards for documentation projects (ADR-041)
coding_standards:
  file_size:
    soft_limit: 500
    note: "lines per markdown file - keep docs focused"
  linting: "markdownlint, yamllint for configs"
  diagrams: "Mermaid preferred (text-based, version controlled)"
  style:
    - "ATX-style headers (#)"
    - "One sentence per line (for git diffs)"

# v8.8.0: Standard deliverables for documentation projects (ADR-034)
deliverables_template:
  - "[ ] Content complete"
  - "[ ] asimov lint-docs . (passes)"
  - "[ ] Reviewed/proofread"
  - "[ ] Commit and push"
