# Project Context - Generic
# Generated by: asimov init
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: generic
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "# Add your test command"
  lint: "# Add your lint command"
  format: "# Add your format command"

files:
  source:
    - "src/ - Source code"
  config:
    - "# Add your config files"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Follow project conventions"
  - "Keep code readable"
  - "Document public APIs"

# v9.3.0: Coding standards for generic projects (ADR-041)
coding_standards:
  file_size:
    soft_limit: 500
    hard_limit: 1000
    note: "lines per file - adjust based on language"
  linting: "# Add your linting tools"
  tests: "# Add your test framework"
  formatting: "# Add your formatter"

# v8.8.0: Standard deliverables for generic projects (ADR-034)
deliverables_template:
  - "[ ] Content complete"
  - "[ ] Reviewed/validated"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
