# Project Context - Node.js / TypeScript
# Generated by: asimov init --type node
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: node
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "npm test"
  lint: "npm run lint"
  format: "npm run format"
  types: "npm run typecheck"
  build: "npm run build"

files:
  source:
    - "src/index.ts - Entry point"
    - "src/lib/ - Library code"
  config:
    - "package.json - Dependencies and scripts"
    - "tsconfig.json - TypeScript configuration"
  tests:
    - "tests/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Strict TypeScript (strict: true)"
  - "Explicit return types for public functions"
  - "No any types in production code"
  - "Prefer const over let"

environment:
  package_manager: "pnpm for efficient installs"
  node_version: "20+"

# v9.3.0: Coding standards for Node.js projects (ADR-041)
coding_standards:
  code:
    file_size:
      soft_limit: 400
      hard_limit: 800
      note: "lines per file - split if exceeding"
    coverage: "80%+"
    linting: "ESLint, TypeScript strict mode"
    tests: "Jest or Vitest, colocated or tests/ directory"
    formatting: "Prettier"
  documentation:
    linting: "markdownlint-cli2"
    style:
      - "ATX-style headers (#)"
      - "One sentence per line (for git diffs)"
  architecture:
    decisions: "ADR format in docs/adr/"
    diagrams: "Mermaid preferred (text-based, version controlled)"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass (npm test)"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] npm run lint (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
