# Project Context - Python
# Generated by: asimov init --type python
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: python
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "pytest"
  lint: "ruff check ."
  format: "ruff format ."
  types: "mypy . (optional)"

files:
  source:
    - "src/{package}/ - Package source"
    - "src/{package}/__init__.py - Package init"
    - "src/{package}/main.py - Entry point"
  config:
    - "pyproject.toml - Project configuration"
  tests:
    - "tests/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Type hints for public APIs"
  - "Docstrings for modules and functions"
  - "No bare except clauses"
  - "Use pathlib over os.path"

environment:
  manager: "uv or pip-tools for fast installs"
  python_version: "3.11+"

# v9.3.0: Coding standards for Python projects (ADR-041)
coding_standards:
  code:
    file_size:
      soft_limit: 500
      hard_limit: 1000
      note: "lines per file - split if exceeding"
    coverage: "90%+"
    linting: "ruff, mypy strict (optional)"
    tests: "pytest, colocated or tests/ directory"
    formatting: "ruff format"
  documentation:
    linting: "markdownlint-cli2"
    style:
      - "ATX-style headers (#)"
      - "One sentence per line (for git diffs)"
  architecture:
    decisions: "ADR format in docs/adr/"
    diagrams: "Mermaid preferred (text-based, version controlled)"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass (pytest)"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] ruff check . (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
