# Project Context - Go
# Generated by: asimov init --type go
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: go
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "go test ./..."
  lint: "golangci-lint run"
  format: "go fmt ./..."
  vet: "go vet ./..."
  build: "go build -o bin/app"

files:
  source:
    - "main.go - Entry point"
    - "cmd/ - CLI commands"
    - "internal/ - Private packages"
    - "pkg/ - Public packages"
  config:
    - "go.mod - Module definition"
    - "go.sum - Dependency checksums"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Return errors, don't panic"
  - "Accept interfaces, return structs"
  - "Keep packages small and focused"
  - "Use context for cancellation"

release:
  static_binary: "CGO_ENABLED=0 go build"
  compression: "UPX --best --lzma (optional)"
