# Project Context - Flutter / Dart
# Generated by: asimov init --type flutter
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: flutter
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"
  visibility: "PRIVATE - check publish_to in pubspec.yaml"

quality:
  test: "flutter test"
  lint: "dart analyze lib/"
  format: "dart format lib/ test/"
  build_android: "flutter build apk"
  build_ios: "flutter build ios"

files:
  source:
    - "lib/main.dart - App entry point"
    - "lib/src/ - Source code"
    - "lib/widgets/ - Reusable widgets"
    - "lib/screens/ - Screen widgets"
    - "lib/services/ - Business logic"
  config:
    - "pubspec.yaml - Dependencies"
    - "analysis_options.yaml - Lint rules"
  tests:
    - "test/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "60fps minimum - no jank"
  - "Const constructors where possible"
  - "Split large widgets into smaller components"
  - "Use RepaintBoundary for expensive widgets"

platform:
  cupertino_first: "CupertinoPageScaffold, CupertinoNavigationBar, CupertinoButton"
  material_fallback: "Only when Cupertino unavailable"
