# Project Context - Generic
# Generated by: asimov init
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: generic
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "# Add your test command"
  lint: "# Add your lint command"
  format: "# Add your format command"

files:
  source:
    - "src/ - Source code"
  config:
    - "# Add your config files"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Follow project conventions"
  - "Keep code readable"
  - "Document public APIs"
