# Project Context - Node.js / TypeScript
# Generated by: asimov init --type node
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: node
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "npm test"
  lint: "npm run lint"
  format: "npm run format"
  types: "npm run typecheck"
  build: "npm run build"

files:
  source:
    - "src/index.ts - Entry point"
    - "src/lib/ - Library code"
  config:
    - "package.json - Dependencies and scripts"
    - "tsconfig.json - TypeScript configuration"
  tests:
    - "tests/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Strict TypeScript (strict: true)"
  - "Explicit return types for public functions"
  - "No any types in production code"
  - "Prefer const over let"

environment:
  package_manager: "pnpm for efficient installs"
  node_version: "20+"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass (npm test)"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] npm run lint (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
