# Project Context - Python
# Generated by: asimov init --type python
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "{PROJECT_NAME}"
  type: python
  version: "0.1.0"
  tagline: "{PROJECT_TAGLINE}"

quality:
  test: "pytest"
  lint: "ruff check ."
  format: "ruff format ."
  types: "mypy . (optional)"

files:
  source:
    - "src/{package}/ - Package source"
    - "src/{package}/__init__.py - Package init"
    - "src/{package}/main.py - Entry point"
  config:
    - "pyproject.toml - Project configuration"
  tests:
    - "tests/ - Test directory"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Type hints for public APIs"
  - "Docstrings for modules and functions"
  - "No bare except clauses"
  - "Use pathlib over os.path"

environment:
  manager: "uv or pip-tools for fast installs"
  python_version: "3.11+"
