# RoyalBit Asimov - Project Context
# The ethical operating system for Claude's autonomous power

# ═══════════════════════════════════════════════════════════════════════════════
# CODING STANDARDS
# ═══════════════════════════════════════════════════════════════════════════════
# - Unit tests: Keep with code (Rust way: #[cfg(test)] mod tests in same file)
# - Test coverage: 100% mandatory for all functional code
# - No file > 1,000 lines (split into submodules when exceeded)
# - Zero warnings policy
# ═══════════════════════════════════════════════════════════════════════════════

identity:
  name: "royalbit-asimov"
  type: rust
  tagline: "Claude provides velocity, Asimov provides guardrails"
  binary: "asimov"
  crate: "royalbit-asimov"

quality:
  test: "cargo test"
  lint: "cargo clippy -- -D warnings"
  format: "cargo fmt --check"
  build: "cargo build --release"
  e2e: "cargo test --test e2e_tests"

files:
  source:
    - "cli/src/main.rs - CLI entry point (clap)"
    - "cli/src/lib.rs - Library exports"
    - "cli/src/protocols/mod.rs - Hardcoded protocols (ADR-031)"
    - "cli/src/validator.rs - Protocol and schema validation"
    - "cli/src/templates.rs - Project templates (rust, python, node, etc.)"
    - "cli/src/schemas/ - YAML schema definitions"
  config:
    - "cli/Cargo.toml - Dependencies and crate metadata"
  docs:
    - "README.md - Project overview"
    - "CHANGELOG.md - Release history"
    - "docs/SPECIFICATION.md - Full specification"
    - "docs/adr/ - Architecture Decision Records"
  tests:
    - "cli/tests/e2e_tests.rs - End-to-end tests"

patterns:
  - "Result<T, E> for errors, no panics"
  - "thiserror for custom errors"
  - "No unwrap() in library code"
  - "Protocols hardcoded, not configurable (ADR-031)"
  - "ADR for all architecture decisions"

release:
  workflow: ".github/workflows/release.yml"
  triggers: "git tag v*"
  platforms:
    - x86_64-unknown-linux-gnu (UPX)
    - aarch64-unknown-linux-gnu
    - x86_64-apple-darwin
    - aarch64-apple-darwin
    - x86_64-pc-windows-msvc (UPX)
  publish:
    - GitHub Releases (binaries + checksums)
    - crates.io (royalbit-asimov)

ci:
  workflow: ".github/workflows/ci.yml"
  jobs:
    - test (cargo test)
    - lint (clippy, fmt)
    - build (all platforms)
    - validate (asimov validate)
    - auto-release (create tag when version changes)
